import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GameProvider } from "@/components/contexts/Gamecontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-whiteGray ${geistMono.variable} overflow-x-hidden antialiased h-screen`}
      >
        <GameProvider>
          {children}
        </GameProvider>
      </body>
    </html>
  );
}
